### PR TITLE
Instruction cache at wide cluster port

### PR DESCRIPTION
**Pull request by zarubaf**
Now that we have the wide DMA port it (can) make sense to actually
perform icache refills from that port, this potentially cuts down the
re-fill latency a couple of cycles.

More importantly, in case there is a read-only cache on the wide
network, it makes use of the same.

(Based on #191)

### CODE REVIEW

**Comment by zarubaf** [comment]
@niwis Anything you want to add/change?

**Review by niwis — APPROVED** [review]
Looks good to me! My only concern is that instruction fences remain effective, what is the solution there? Flushing the full quadrant? (Sorry for the delayed reply, the PR slipped my attention)

**Comment by niwis** [comment]
And is it possible to access the SPM via the wide crossbar?

**Comment by zarubaf** [comment]
> Looks good to me! My only concern is that instruction fences remain effective, what is the solution there? Flushing the full quadrant? (Sorry for the delayed reply, the PR slipped my attention)

I don't think anything should change for that. The instruction cache can still be invalidated very much the same way (`fence.i`).



> And is it possible to access the SPM via the wide crossbar?

That is a very valid point. Currently, it can't, but it seems that this needs to change anyway (see the discussion yesterday on the atomics supported in L2). I will open a new issue for that, it should be relatively easy to fix (famous last words).

**Comment by niwis** [comment]
Okay :-) And I guess the same then also goes for the bootrom, debug module and other peripherals

**Comment by niwis** [comment]
Looks good to me after #200

**Pull request merged**
