### PR TITLE
banshee: Check if return value was written at all

### PR DESCRIPTION
**Pull request by SamuelRiedel**
The `exit_code` register is initialized to 0 in Banshee. If Banshee stops before writing a return value, it will look as if the execution was successful. This patch checks the LSB of the `exit_code` to make sure the return value was actually written. If we have debug prints enabled, it will generate a warning, otherwise, it will just set Banshee's return value to 1.

### CODE REVIEW

**Review by paulsc96 — APPROVED** [review]
Good catch! My only suggestion is to maybe choose a return code that will stand out more, but that is arguable.

**Comment by SamuelRiedel** [comment]
Yes, I thought about that as well, but I did not know what would be a good return value. Maybe `0xDEADBEEF` or `0xBADCAB1E`, but this would get lost since the shell uses decimal. Maybe just something like `1234`?

**Comment by paulsc96** [comment]
I think most shells (including bash) truncate to unsigned bytes, so 0-255 is viable.

To give it a Swiss touch, how about 117, since this is illegal behavior :)

**Comment by SamuelRiedel** [comment]
I like it. :+1:

**Pull request merged**
