### PR TITLE
banshee: Implement AMOs

### PR DESCRIPTION
**Pull request by SamuelRiedel**
Add support for atomic operations. Currently supported are all RV32 atomics except LR/SC.

Todo:
- [ ] Implement LR/SC
- [x] Add unittests
- [x] Update changelog

### CODE REVIEW

**Review by fabianschuiki — APPROVED** [review]
This looks very nice to me! The CI is likely breaking at the moment due to an issue in executing the banshee unit tests. Is this PR ready to merge from your side @SamuelRiedel ? I'm happy to merge it in already because it might take some time until we've figured out the CI issue.

**Comment by fabianschuiki** [comment]
Forgot to mention: Can you briefly rebase onto master again?

**Comment by SamuelRiedel** [comment]
From my side, this can be merged. We can tackle the LR/SC instructions in a new PR. I rebased and updated the changelog.

**Comment by fabianschuiki** [comment]
Great, thanks a lot! Merging.

**Pull request merged**
