### PR TITLE
sw/vendor: Add `riscv-opcodes`

### PR DESCRIPTION
**Pull request by oakentling**
- Add riscv-opcodes repository using vendor in `/sw/vendor`
- Update generate-opcodes.sh to work with new structure of `/sw/vendor/riscv-opcodes`

There have been some name changes which affect some files in `sw/banshee/tests/runtime`, `sw/vendor/riscv-isa-sim/{fesvr,riscv}`.

### CODE REVIEW

**Comment by oakentling** [comment]
@SamuelRiedel I created the draft pull request for the snitch opcode integration. Can you run the CI?

**Review by SamuelRiedel — APPROVED** [review]
LGTM

**Comment by oakentling** [comment]
Can we merge into another branch than master? Because I have a [draft PR](https://github.com/pulp-platform/snitch/pull/411) that builds on this and I'd like to check if CI works for that PR.
If not, is there an estimate how long it will take until this can be merged? Because I'll likely finish my bachelor thesis in a month and would be glad to not have open PRs after :)

**Comment by paulsc96** [comment]
> Can we merge into another branch than master? Because I have a [draft PR](https://github.com/pulp-platform/snitch/pull/411) that builds on this and I'd like to check if CI works for that PR. If not, is there an estimate how long it will take until this can be merged? Because I'll likely finish my bachelor thesis in a month and would be glad to not have open PRs after :)

If you can give me till next week (say, Monday) I can create a reasonable preview branch for you and everyone else to merge into. Right now, things are too turbulent.

**Comment by oakentling** [comment]
Yes, that is not a problem. Thank you.

**Comment by oakentling** [comment]
Thank you :smiley:

**Pull request merged**
