### PR TITLE
util: Add trace annotation script

### PR DESCRIPTION
**Pull request by noah95**
A script to annotate Snitch traces with source code

image

### CODE REVIEW

**Review by zarubaf — APPROVED** [review]
Amazing! Love it!

**Comment by noah95** [comment]
While at it, added the caching to `tracevis.py` and moved it to `util/trace`

**Comment by SamuelRiedel** [comment]
Fantastic :tada:. Don't forget to add the caching package to the python requirements.

**Comment by noah95** [comment]
> Fantastic tada. Don't forget to add the caching package to the python requirements.

`functools` is part of the python standard library since 2.7

**Pull request merged**
