### PR TITLE
Tracevis

### PR DESCRIPTION
**Pull request by SamuelRiedel**
Add a script to visualize Snitch's traces with [Trace-Viewer](https://github.com/catapult-project/catapult/tree/master/tracing)

### CODE REVIEW

**Comment by zarubaf** [comment]
That is really, really cool! Would you mind adding a sentence to the docs on how to use it and maybe (only as an extra plus) a Screenshot? I think we want to show off 😃

**Review by zarubaf — APPROVED** [review]
😍

**Comment by noah95** [comment]
Hard to get a good screenshot @zarubaf but here you go:

tracevis

**Review by noah95 — APPROVED** [review]
Tested and working with banshee and RTL traces

**Comment by zarubaf** [comment]
Freakin‘ love it!

**Comment by SamuelRiedel** [comment]
> That is really, really cool! Would you mind adding a sentence to the docs on how to use it and maybe (only as an extra plus) a Screenshot? I think we want to show off smiley

We could even add a full example trace for people to check out in the docs. I added an HTML file containing a full trace of eight cores. However, this might be too much. What do you think?

**Comment by zarubaf** [comment]
A real example is awesome! I re-triggered the CI in the hope the failing `cmake` install is a glitch.

**Comment by SamuelRiedel** [comment]
> A real example is awesome! I re-triggered the CI in the hope the failing `cmake` install is a glitch.

It seems the CI is working, so let's merge this.

**Pull request merged**
