### PR TITLE
ci/fpu-tests: Part 1

### PR DESCRIPTION
**Pull request by GiannaP**
These are the first part of adding FPU related tests. Note that this does not include extensive FPU tests, but the end goal is to call every FPU instruction a few times to ensure they are properly decoded and the FPU instruction is in general executed correctly by the FPU.

The following changes have been made:

**FPTests:**
- added FPU CI tests for various FP formats for RTL, generated with the help of the flexfloat library. Note that Banshee has some rounding issues (FP rounding mode of host system is not accessible), therefore, the CI tests for Banshee are currently disabled. Banshee rounding issues need further investigation in another PR.

Based on these added CI tests a few bugs were fixed in RTL (and a few in Banshee).

**FPNew:**
- update to new version which fixes vfmin/vfmax instructions

**FP instruction decoder:**
- fix decoding for FCVT.H.W

**Banshee:**
- fix VFMRE.S VFMRER.S according to RISC-V specification
- fix FNMADD.S/D/Q and FNMSUB.S/D/Q to follow RISC-V specification

**Varia:**
- add Makefile target for snRuntime tests for questasim

### CODE REVIEW

**Review by fischeti — APPROVED** [review]
The SW part LGTM!

**Review by paulsc96 — APPROVED** [review]
Looks okay to me. Just two questions:

* How long do you think these added tests will run? What will be the impact on CI runtime?
* Is it maybe a better idea to initialize the error return code to the number of values checked and count down / substract errors? This is much more robust in case of catastrophic test failure (I speak from painful experience here).

**Comment by GiannaP** [comment]
> Looks okay to me. Just two questions:
> 
>     * How long do you think these added tests will run? What will be the impact on CI runtime?
CI test for RTL ran these tests for this branch already: all unit tests take **7min 29s**. The unit tests on RTL on other branches took around **7-8min** from what I see. They are only executed for the LLVM toolchain. When ignoring compilation time, the tests take a fairly low amount of time:

```
      Start 16: snRuntime-rtl-snRuntime-rtl-fp8_comparison_vector
16/38 Test #16: snRuntime-rtl-snRuntime-rtl-fp8_comparison_vector ........   Passed    3.92 sec
      Start 17: snRuntime-rtl-snRuntime-rtl-fp8_comparison_scalar
17/38 Test #17: snRuntime-rtl-snRuntime-rtl-fp8_comparison_scalar ........   Passed    3.58 sec
      Start 18: snRuntime-rtl-snRuntime-rtl-fp8_computation_scalar
18/38 Test #18: snRuntime-rtl-snRuntime-rtl-fp8_computation_scalar .......   Passed    3.76 sec
      Start 19: snRuntime-rtl-snRuntime-rtl-fp8_computation_vector
19/38 Test #19: snRuntime-rtl-snRuntime-rtl-fp8_computation_vector .......   Passed    5.20 sec
      Start 20: snRuntime-rtl-snRuntime-rtl-fp8alt_comparison_vector
20/38 Test #20: snRuntime-rtl-snRuntime-rtl-fp8alt_comparison_vector .....   Passed    3.88 sec
      Start 21: snRuntime-rtl-snRuntime-rtl-fp8alt_comparison_scalar
21/38 Test #21: snRuntime-rtl-snRuntime-rtl-fp8alt_comparison_scalar .....   Passed    3.39 sec
      Start 22: snRuntime-rtl-snRuntime-rtl-fp8alt_computation_scalar
22/38 Test #22: snRuntime-rtl-snRuntime-rtl-fp8alt_computation_scalar ....   Passed    4.01 sec
      Start 23: snRuntime-rtl-snRuntime-rtl-fp8alt_computation_vector
23/38 Test #23: snRuntime-rtl-snRuntime-rtl-fp8alt_computation_vector ....   Passed    4.72 sec
      Start 24: snRuntime-rtl-snRuntime-rtl-fp16_comparison_vector
24/38 Test #24: snRuntime-rtl-snRuntime-rtl-fp16_comparison_vector .......   Passed    3.95 sec
      Start 25: snRuntime-rtl-snRuntime-rtl-fp16_comparison_scalar
25/38 Test #25: snRuntime-rtl-snRuntime-rtl-fp16_comparison_scalar .......   Passed    3.36 sec
      Start 26: snRuntime-rtl-snRuntime-rtl-fp16_computation_scalar
26/38 Test #26: snRuntime-rtl-snRuntime-rtl-fp16_computation_scalar ......   Passed    3.98 sec
      Start 27: snRuntime-rtl-snRuntime-rtl-fp16_computation_vector
27/38 Test #27: snRuntime-rtl-snRuntime-rtl-fp16_computation_vector ......   Passed    4.59 sec
      Start 28: snRuntime-rtl-snRuntime-rtl-fp16alt_comparison_vector
28/38 Test #28: snRuntime-rtl-snRuntime-rtl-fp16alt_comparison_vector ....   Passed    3.78 sec
      Start 29: snRuntime-rtl-snRuntime-rtl-fp16alt_comparison_scalar
29/38 Test #29: snRuntime-rtl-snRuntime-rtl-fp16alt_comparison_scalar ....   Passed    3.38 sec
      Start 30: snRuntime-rtl-snRuntime-rtl-fp16alt_computation_scalar
30/38 Test #30: snRuntime-rtl-snRuntime-rtl-fp16alt_computation_scalar ...   Passed    3.71 sec
      Start 31: snRuntime-rtl-snRuntime-rtl-fp16alt_computation_vector
31/38 Test #31: snRuntime-rtl-snRuntime-rtl-fp16alt_computation_vector ...   Passed    4.91 sec
      Start 32: snRuntime-rtl-snRuntime-rtl-fp32_comparison_vector
32/38 Test #32: snRuntime-rtl-snRuntime-rtl-fp32_comparison_vector .......   Passed    3.77 sec
      Start 33: snRuntime-rtl-snRuntime-rtl-fp32_comparison_scalar
33/38 Test #33: snRuntime-rtl-snRuntime-rtl-fp32_comparison_scalar .......   Passed    3.72 sec
      Start 34: snRuntime-rtl-snRuntime-rtl-fp32_computation_scalar
34/38 Test #34: snRuntime-rtl-snRuntime-rtl-fp32_computation_scalar ......   Passed    3.71 sec
      Start 35: snRuntime-rtl-snRuntime-rtl-fp32_computation_vector
35/38 Test #35: snRuntime-rtl-snRuntime-rtl-fp32_computation_vector ......   Passed    4.64 sec
      Start 36: snRuntime-rtl-snRuntime-rtl-fp32_conversions_scalar
36/38 Test #36: snRuntime-rtl-snRuntime-rtl-fp32_conversions_scalar ......   Passed    4.21 sec
      Start 37: snRuntime-rtl-snRuntime-rtl-fp64_conversions_scalar
37/38 Test #37: snRuntime-rtl-snRuntime-rtl-fp64_conversions_scalar ......   Passed    4.17 sec
```


> 
>     * Is it maybe a better idea to initialize the error return code to the number of values checked and count down / substract errors? This is much more robust in case of catastrophic test failure (I speak from painful experience here).

Mhmm good point. This would make it a bit more robust. I think I will implement that before merging.

**Comment by lucabertaccini** [comment]
LGTM!

**Pull request merged**
