### PR TITLE
util: Add spike-dasm disassembler with Snitch extensions supported

### PR DESCRIPTION
**Pull request by noah95**
This adds `riscv-isa-sim` as a submodule with modifications to spike-dasm to support Snitch extensions (dma, frep, ssr, smallfloat).

```
80010160 ... # dmsrc   a0, zero
80010164 ... # dmdst   a7, zero
80010168 ... # dmstr   a3, a3
8001016c ... # dmrep   a6
80010170 ... # dmcpy   a1, a3, a1
800016c4 ... # frep.o  s7, 7, 0, 0b0000
80010098 ... # scfgwi  t0, 32
8001009c ... # scfgri  t1, 32
800100e4 ... # scfgw   t1, t0
800100e8 ... # scfgr   t3, t0
80001724 ... # vfsum.s ft10, fa2
80001728 ... # vfcpka.h.s ft3, fa3, fa4
80001724 ... # vfsum.s ft10, fa2
80001728 ... # vfcpka.h.s ft3, fa3, fa4
8000172c ... # vfcpkb.h.s ft3, fa5, fa6
80001730 ... # vfcpka.h.s ft4, fa7, ft8
80001734 ... # vfcpkb.h.s ft4, ft9, ft10
```

The `riscv-isa-sim` used is an old version that is ~1k commits behind upstream. Problem being, that the upstream version has much more extensions builtin that could collide with our extensions and is more complicated to extend.

Shall we (A) leave it as a submodule or (B) copy-in the code as is done with `riscv-opcode`? If (A), move the upstream repo to the pulp-platform namespace?

### CODE REVIEW

**Review by fischeti — APPROVED** [review]
Awesome!

**Comment by zarubaf** [comment]
Yes, let's copy the sources in. Submodules confuse people in my experience and I do not see us contributing back a lot of those extensions.

**Comment by zarubaf** [comment]
Would also be nice if we build this version in the container instead of the upstream one.

**Comment by noah95** [comment]
> Would also be nice if we build this version in the container instead of the upstream one.

k, done.

**Review by zarubaf — APPROVED** [review]
:+1:

**Pull request merged**
