### PR TITLE
solder: Make `xbar` configurable

### PR DESCRIPTION
**Pull request by zarubaf**
This PR adds the feature to parameterize the crossbar's in Occamy. Since the Snitch crossbars aren't (yet) generated this is still hard-coded. @thommythomaso please see if this fits your needs.

### CODE REVIEW

**Comment by niwis** [comment]
Is it possible that some old files slipped into the PR? (i.e. the `const_cache` schema files)

**Comment by zarubaf** [comment]
Indeed, in general, I think there has been some stale schema documentation accumulating...

**Comment by zarubaf** [comment]
Okay @thommythomaso ?

**Comment by thommythomaso** [comment]
Looks good to me!

**Pull request merged**
